### ISSUE TITLE
}while(address < _cfgAddrStop && check != 0xFF && check != 0x00 && done < num);

### ISSUE THREAD

**Issue by martinm466** [adlerweb/asysbus#10]
...Arduino\libraries\asysbus-master\asb.cpp: In member function 'bool ASB::hookAttachModule(ASB_IO*)':

...Arduino\libraries\asysbus-master\asb.cpp:326:92: error: 'done' was not declared in this scope

}while(address < _cfgAddrStop && check != 0xFF && check != 0x00 && done < num);

Ausserdem versteh ich die Commands nicht richtig:
0x51 | 1 | 1 Bit Message (e.g. on/off)
im Sketch simple wird es volgendermaßen gelöst
 {ASB_CMD_1B, 1};
Wie komm ich von 1B (wahrscheinlich HEX) auf 51 (wahrscheinlich DEZ)?
Ich kann mir nur 27 erklären aber das ist wohl nicht richtig

Vielen Dank für eine Lösung / Erklärung

**Comment by adlerweb** [comment]
Ja, da scheinen ein paar Zeilen im Commit 5ca27173cf68428797a1ddf957d06e1fbf3c831a zu fehlen. Schaue ich mir zeitnah an. Im Zweifel erst mal die vorherige Version nutzen:
`}while(address < _cfgAddrStop && check != 0xFF && check != 0x00);`

1B ist keine Zahl sondern nur eine Abkürzung für "1-Bit"(-Nachricht). Die Nummer 0x51 ist eher historisch - um nicht mit Nachrichten des Ursprungsprojektes iSysBus zu kollidieren hatte ich damals bei 0x50 angefangen zu zählen.
