### ISSUE TITLE
compiling problem

### ISSUE THREAD

**Issue by Lukiflan** [adlerweb/asysbus#3]
[compiling error.txt](https://github.com/adlerweb/asysbus/files/1823100/compiling.error.txt)

Die Definition der Methode "begin" in der Library MCP_CAN (mcp_can.h) von adlerweb nimmt von asysbus entweder ein oder drei argumente entgegen:
```
    byte begin(byte idmodeset, byte speedset, byte clockset);    // Initilize controller prameters
    byte begin(byte speedset);                                   // Initilize controller prameters
```

 Die Methode "begin", (asb_can.cpp) stellt der ersten aber zwei zur Verfügung:
```
    byte ASB_CAN::begin() {
        lastErr = _interface.begin(_speed, _clockspd);
    }
```

Das Beispiel "simple" von asysbus lässt sich somit nicht kompilieren. Kann es sein, dass die Version des CAN_BUS_Shield nicht mit derjenigen von asysbus übereinstimmt.

**Comment by adlerweb** [comment]
Die [Upstream-Version der CAN-Library](https://github.com/Seeed-Studio/CAN_BUS_Shield) hat vor einiger Zeit die lokalen Änderungen übernommen, seit Commit https://github.com/adlerweb/asysbus/commit/d3f2bdfb1212c612c2271de07464f63b337048d9 wird daher statt des lokalen Forks die "offizielle" Version genutzt.
