### ISSUE TITLE
The simple example cannot be compiled. 

### ISSUE THREAD

**Issue by TheGreyDiamond** [adlerweb/asysbus#7]
[log.txt](https://github.com/adlerweb/asysbus/files/2257429/log.txt)

_(sorry german log)_

**Comment by adlerweb** [comment]
`C:\Users\*****\Documents\Arduino\libraries\asysbus-master\asb_can.cpp:61:53: error: no matching function for call to 'MCP_CAN::begin(byte&, byte&)'`
Vermutlich veraltete CAN-Library. Mit aktuellem Stand von https://github.com/Seeed-Studio/CAN_BUS_Shield keine Probleme
(Probably an outdated CAN library. Current upstream works for me)

**Comment by enricoh831** [comment]
Ähnliches Problem. In asb.cpp Zeile 324 "done' was not declaration in this scope.

**Comment by TheGreyDiamond** [comment]
Bei mir geht es irgendwie bei manchen Computer nicht... Mal eine Übersicht:
Windows 10 Pro (Laptop) OK
Windows 7 Home (Laptop) FEHLER
Mint (Version weiss ich gerade net, LAPTOP) OK
Komisch..

**Comment by enricoh831** [comment]
Bei mir läuft zorin OS. Könnte es eventuell ein Schreibfehler in der lib sein auf den die System unterschiedlich sensible reagieren

**Comment by enricoh831** [comment]
Habe gerade in der asb.h nach Fehlern gesucht
Nach dem ändern kamen andere Fehler. Nach dem ich wieder auf ursprünglich geändert haben konte ich es kompilieren.

**Comment by adlerweb** [comment]
> Ähnliches Problem. In asb.cpp Zeile 324 "done' was not declaration in this scope.

Das war was anderes - kaputter commit, sollte inzwischen behoben sein (72154dd5ef176582826f3198ef6563d4e7b48d78)

Ich kann die Probleme weiterhin nicht nachvollziehen - auf einer frischen Arduino-Installation kompiliert es momentan sauber. Ganz sicher, dass die aktuellen Versionen dieser Library und von https://github.com/Seeed-Studio/CAN_BUS_Shield drauf sind und nicht noch irgendwo eine alte Version im Arduino-Ordner liegt?

**Comment by TheGreyDiamond** [comment]
Es stört mich auch nicht weiter, da es auf meiner Hauptarbeitsstation geht. Die anderen Laptops muss ich mir nochmal genauer angucken!
